### ISSUE TITLE
Filter method can leak memory

### ISSUE THREAD

**Issue by pwiecz** [jamespwilliams/slicetricks#1]
`Filter` is not assigning zero values to the trailing elements (like `FilterZeroAlloc` does).
It should be noted in the method's comment or change.

**Comment by jamespwilliams** [comment]
Thanks, I'll make `Filter` assign zero values to the trailing elements.

And, having looked again, neither `Filter` nor `FilterZeroAlloc` perform any allocations. `Filter` is a bit simpler (and slightly faster in my benchmarks), so I'll just remove `FilterZeroAlloc`.
